spring:
  application:
    name: greeting-service
server:
  port: 8082
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
# Log Output to a file
logging:  file:    path: "${user.dir}/${spring.application.name}}/log/"
    name: "${spring.application.name}.log"